# Default values for testbench

namespace:
  # Create namespace if it doesn't exist
  create: true
  # Namespace name
  name: testkube

image:
  repository: ghcr.io/agentic-layer/testbench/testworkflows
  # Overrides the image tag whose default is the chart appVersion
  tag: ""
  pullPolicy: IfNotPresent

# Grafana dashboard configuration
grafana:
  # ConfigMap name for dashboards
  dashboardConfigMapName: grafana-testkube-dashboard
  # Target namespace for Grafana dashboards
  dashboardNamespace: monitoring
