# See https://pre-commit.com for more information
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents]
        exclude: ^chart/templates/
      - id: check-ast
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: name-tests-test
        args: [ --pytest-test-first ]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: requirements-txt-fixer
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: python-lint
        name: python-lint
        language: system
        entry: "uv run poe lint"
        types_or: [ python ]
        pass_filenames: false

      - id: python-ruff
        name: python-ruff
        language: system
        entry: "uv run poe ruff"
        types_or: [ python ]
        pass_filenames: false

      - id: helm-lint
        name: Helm Lint
        entry: helm lint chart/
        language: system
        pass_filenames: false
        files: ^chart/
