apiVersion: testworkflows.testkube.io/v1
kind: TestWorkflowTemplate
metadata:
  name: ragas-visualize-template
  namespace: {{ include "testbench.namespace" . }}
  labels:
    {{- include "testbench.labels" . | nindent 4 }}
    {{- include "testbench.workflowLabels" . | nindent 4 }}

spec:
  # Steps to execute
  steps:
    - name: visualize-metrics
      artifacts:
        paths:
          - "data/results/evaluation_report.html"
      run:
        image: {{ include "testbench.image" . }}
        args:
          - visualize.py
          - "{{`{{ workflow.name }}`}}"
          - "{{`{{ execution.id }}`}}"
          - "{{`{{ execution.number }}`}}"
