apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - lgtm.yaml
  - lgtm-otelcol-config.yaml
  - weather-agent.yaml
  - data-server/
  - ../base
  - ragas-evaluation-workflow.yaml
