apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - lgtm/
  - weather-agent.yaml
  - dataset.yaml
  - multi-turn-metrics-configmap.yaml
  - multi-turn-workflow.yaml
  - multi-turn-workflow-trigger.yaml
