name: Push
on:
  push:
    tags:
      - 'v*'

env:
  REGISTRY: ghcr.io

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: 'write'
      contents: 'write'

    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v5'
        with:
          fetch-depth: 0 # required to fetch all history for all branches and tags

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Docker Build & Push'
        run: |
          make docker-buildx

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v3

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/testbench/testworkflows
          tags: |
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=raw,value=latest

      - name: 'Build & Push TestWorkflows Image'
        uses: docker/build-push-action@v5
        with:
          context: ./testworkflows
          file: ./testworkflows/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: 'Setup Flux CLI'
        uses: fluxcd/flux2/action@main

      - name: 'Flux Build & Push'
        run: |
          make flux-push

      - name: 'Flux Tag Latest'
        run: |
          make flux-tag-latest

      - name: 'Build Installer'
        run: |
          make build-installer

      - name: 'Create Release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes \
              dist/install.yaml
